### ISSUE TITLE
demo例子css兼容性太差了

### ISSUE THREAD

**Issue by longboy** [linweiwei123/multipages-generator#5]
demo例子css兼容性太差了吧，iOS8系统的打开直接乱了：
![wechatimg9](https://user-images.githubusercontent.com/6941888/38122298-c869f7b6-3406-11e8-8c4d-8c949ef7cb4b.jpeg)

**Comment by gogogodeng** [comment]
我用微信打开都是错位的。。。

**Comment by linweiwei123** [comment]
@longboy 已经兼容ios 8了。 修改内容：
  postcss.config,js 增加
  autoprefixer: {
            browsers: [
                'last 2 versions',
                'iOS >= 8'
            ]
        }

**Comment by linweiwei123** [comment]
@gogogodeng 能否告知下什么系统和版本呢。

**Comment by linweiwei123** [comment]
@gogogodeng 刚刚增加了ios 8的兼容。你看看是否还存在，如果还存在能否提供下系统和版本

**Comment by gogogodeng** [comment]
我的是安卓8.0 小米6

**Comment by linweiwei123** [comment]
@gogogodeng 好的，谢谢

**Comment by fantasthu** [comment]
@linweiwei123 加个微信聊下你这个项目呗,我微信号 huwenzhi4224

**Comment by linweiwei123** [comment]
@fantasthu 好的，手机被别人拿去做ios测试了，一会加下你
