### ISSUE TITLE
运行有问题

### ISSUE THREAD

**Issue by langgo** [linweiwei123/multipages-generator#6]
在我的环境下，运行出现了问题。

现象 打开 localhost:2000 之后，得不到响应，就一直在那里转圈。

```
$ node --version
v8.9.4
```

```
$ yarn run watch:viewport
yarn run v1.5.1
$ rimraf public &&cross-env ENV=dev PROJECT_NAME=viewport node ./tools/webpack.watch.js
Build completed in 10.644s

[webpack]: build done!


[Browsersync] Proxying: http://localhost:4000
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:2000
    External: http://192.168.1.33:2000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.33:3001
 -------------------------------------
[Browsersync] Watching files...

```

```
$ yarn run start
yarn run v1.5.1
$ nodemon ./bin/www
[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
```

**Comment by linweiwei123** [comment]
@langgo 是的，需要调整下顺序，$ yarn run start 然后 $ yarn run watch:viewport  这样看看

**Comment by linweiwei123** [comment]
@langgo 前端起了一个热启动的服务，通过代理访问服务端的服务，顺序上是服务端先启动。你试试。文档已更新

**Comment by wujunchuan** [comment]
按照这样的顺序：
1. 先启动服务端服务`npm run  start`
2. 再启动前端热启动`npm run watch:viewport`

就算这么做的话还会有一个问题，那就是一直等待请求。

抓了下包显示：
![](https://ws3.sinaimg.cn/large/006tNbRwgy1fpuw4uxagmj30gm0a3wej.jpg)

可见请求已经发出，一直等待服务器响应，我猜想是因为服务器在返回响应前的那瞬间，服务器重启了。
查看一下日志果然如此
![](https://ws2.sinaimg.cn/large/006tNbRwgy1fpuw5hww4rj31hb09s0tu.jpg)

设想
可以把启动 `browser-sync`这个动作前置，而不是放在webpack compile后的回调，
这样子保证nodemon重启服务器前，浏览器已经接收到包含 `browser-sync`运行的html文件

稍晚提个PR你运行看看可不可以， @linweiwei123

**Comment by linweiwei123** [comment]
@wujunchuan 是的，编译后服务端检测到文件变化又重启了一次

**Comment by linweiwei123** [comment]
此方案已经解决：
1, 先启动服务端 npm run start;
2, 再启动前端 npm run watch:viewport
